### ISSUE TITLE
getting eppic jar file for parsing uniprot xml files

### ISSUE THREAD

**Issue by kumar-physics** [eppic-team/eppic-pipeline#1]
There should be an automated way to get the latest eppic jar file to parse uniprot xml files during eppic pipeline.

**Comment by josemduarte** [comment]
At the moment the "official" way to do it would be to get it from our web server, which should always have the current release version. So this should work:

```
wget http://eppic-web.org/downloads/eppic.zip
unzip eppic.zip
java -cp eppic-cli-2.1.2-SNAPSHOT/lib/uber-eppic-cli-2.1.2-SNAPSHOT.jar eppic.tools.WriteUniqueUniprots
```

That would only work for the current release. For other releases one would have to compile the jar using maven, but that can be automatic too:

```
git clone https://github.com/eppic-team/eppic.git
cd eppic
# v2.1.2 is the tag name, any other version tags can be used
git checkout v2.1.2
# this compiles the whole project
mvn install
# the jar should be in the target dir
ls eppic-cli/target/uber-eppic-cli-2.1.2-SNAPSHOT.jar
```
